//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.11.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "mandatoryFileUploadControl"
	/// <summary>Mandatory File Upload Control</summary>
	public partial interface IMandatoryFileUploadControl : IPublishedContent
	{
		/// <summary>Upload File</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent UploadFile { get; }
	}

	/// <summary>Mandatory File Upload Control</summary>
	[PublishedModel("mandatoryFileUploadControl")]
	public partial class MandatoryFileUploadControl : PublishedContentModel, IMandatoryFileUploadControl
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new const string ModelTypeAlias = "mandatoryFileUploadControl";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MandatoryFileUploadControl, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public MandatoryFileUploadControl(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Upload File
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("uploadFile")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent UploadFile => GetUploadFile(this);

		/// <summary>Static getter for Upload File</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetUploadFile(IMandatoryFileUploadControl that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("uploadFile");
	}
}
