//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.11.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Photo Album</summary>
	[PublishedModel("photoAlbum")]
	public partial class PhotoAlbum : PublishedContentModel, IPhotoAlbums
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new const string ModelTypeAlias = "photoAlbum";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PhotoAlbum, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PhotoAlbum(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Album Cover
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("albumCover")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent AlbumCover => global::Umbraco.Web.PublishedModels.PhotoAlbums.GetAlbumCover(this);

		///<summary>
		/// Album Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("albumDescription")]
		public string AlbumDescription => global::Umbraco.Web.PublishedModels.PhotoAlbums.GetAlbumDescription(this);

		///<summary>
		/// Album Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("albumTitle")]
		public string AlbumTitle => global::Umbraco.Web.PublishedModels.PhotoAlbums.GetAlbumTitle(this);

		///<summary>
		/// Photos Folder: Select the folder with the photos
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("photosFolder")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PhotosFolder => global::Umbraco.Web.PublishedModels.PhotoAlbums.GetPhotosFolder(this);
	}
}
