//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.11.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "youtubeEmbedControls"
	/// <summary>Youtube Embed Controls</summary>
	public partial interface IYoutubeEmbedControls : IPublishedContent
	{
		/// <summary>Video Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		global::System.Web.IHtmlString VideoDescription { get; }

		/// <summary>Video Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		string VideoTitle { get; }

		/// <summary>Video Url</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		string VideoUrl { get; }
	}

	/// <summary>Youtube Embed Controls</summary>
	[PublishedModel("youtubeEmbedControls")]
	public partial class YoutubeEmbedControls : PublishedContentModel, IYoutubeEmbedControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new const string ModelTypeAlias = "youtubeEmbedControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<YoutubeEmbedControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public YoutubeEmbedControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Video Description: Enter the Video Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("videoDescription")]
		public global::System.Web.IHtmlString VideoDescription => GetVideoDescription(this);

		/// <summary>Static getter for Video Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public static global::System.Web.IHtmlString GetVideoDescription(IYoutubeEmbedControls that) => that.Value<global::System.Web.IHtmlString>("videoDescription");

		///<summary>
		/// Video Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("videoTitle")]
		public string VideoTitle => GetVideoTitle(this);

		/// <summary>Static getter for Video Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public static string GetVideoTitle(IYoutubeEmbedControls that) => that.Value<string>("videoTitle");

		///<summary>
		/// Video Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		[ImplementPropertyType("videoUrl")]
		public string VideoUrl => GetVideoUrl(this);

		/// <summary>Static getter for Video Url</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.1")]
		public static string GetVideoUrl(IYoutubeEmbedControls that) => that.Value<string>("videoUrl");
	}
}
